## 배열 Copy와 View

In [1]:
import numpy as np

In [2]:
# Copy
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [3]:
# View
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [4]:
# View change
arr = np.array([1,2,3,4,5])
x = arr.view()
x[0] = 31
print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


##base

In [5]:
# 배열이 데이터를 소유하는지 여부를 확인하려면 기본 속성의 값을 인쇄
# 복사본이 반환 되면 None
# View는 원래 배열을 반환

arr = np.array([1,2,3,4,5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]
