## 데이터 유형

In [1]:
import numpy as np

## Python의 데이터 유형

- `strings` :  텍스트 데이터를 나타내는 데 사용되며 텍스트는 따옴표 안에 표시된다. ex) “ABCD”
- `integer`:  정수를 표현하는데 사용된다. ex) 1.2 , 42.42
- `float`: 실수를 표현하는데 사용된다.
- `complex` : 복소수를 나타내는 데 사용된다. ex) 1.0 + 2.0j, 1.5 + 2.5j

## NumPy의 데이터 유형

- `i`  - 정수
- `b` - 불린
- `u` - 부호 없는 정수
- `f` - 실수
- `c` - 복잡한 실수
- `m` - 두 날짜나 시간의 차이인 기간
- `M` - 날짜 시간
- `O` - 객체(대문자 O)
- `S` - string(대문자 S)
- `U` - 유니코드 문자열(대문자 U)
- `V` - 다른 유형에 대한 고정된 메모리(대문자 V)

In [4]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr)
print(arr.dtype)
print(type(arr))

['apple' 'banana' 'cherry']
<U6
<class 'numpy.ndarray'>


In [6]:
arr = np.array([1,2,3,4,])
print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4]
int64
<class 'numpy.ndarray'>


# 정의된 데이터 유형으로 배열 생성

In [7]:
arr = np.array([1,2,3,4], dtype='S')
print(arr)
print(arr.dtype)
print(type(arr))

[b'1' b'2' b'3' b'4']
|S1
<class 'numpy.ndarray'>


In [10]:
# 데이터 유형이 4바이트 정수인 배열
arr = np.array([1,2,3,4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# 기존 array의 데이터 유형 변환

In [13]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')     #int로 형 변환

print(arr)
print(arr.dtype)
print(newarr)
print(newarr.dtype)

[1.1 2.1 3.1]
float64
[1 2 3]
int32


In [14]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)      #boolean으로 형 변환

print(arr)
print(arr.dtype)
print(newarr)
print(newarr.dtype)

[1 0 3]
int64
[ True False  True]
bool
