## 배열 정렬

In [1]:
import numpy as np

In [3]:
arr = np.array([3,0,2,1,4])
print(np.sort(arr)) # 오름차순

[0 1 2 3 4]


In [4]:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr)) # 오름차순

['apple' 'banana' 'cherry']


In [5]:
# 내림차순 = np.sort()[::-1]
arr = np.array([1,4,5,2,3,9])
print(np.sort(arr)[::-1]) # 내림차순

[9 5 4 3 2 1]


# 2차원 배열 정렬

In [12]:
arr = np.array([[3,2,4],[4,0,3]])
print(arr)
print(arr.shape)
print("------")
print(np.sort(arr)) # 오름차순

[[3 2 4]
 [4 0 3]]
(2, 3)
------
[[2 3 4]
 [0 3 4]]
