## 배열 검색

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [3]:
# 짝수 인덱스 찾기
arr = np.array([1,2,3,4,5,6,7,8,])
x = np.where(arr % 2 == 0)
print(x)

(array([1, 3, 5, 7]),)


In [4]:
# 홀수 인덱스 찾기
arr = np.array([1,2,3,4,5,6,7,8,])
x = np.where(arr % 2 == 1)
print(x)

(array([0, 2, 4, 6]),)


# 정렬 검색

In [5]:
arr = np.array([6,7,8,9])
x = np.searchsorted(arr, 7)
print(x)

1


In [6]:
# 오른쪽부터 찾기
arr = np.array([6,7,8,9])
x = np.searchsorted(arr, 7, side='right')  #오른쪽기준으로 인덱스 2에 7을 삽입
print(x)

2


# 다중값

In [7]:
# 값 2, 4, 6을 삽입해야 하는 인덱스 찾기
arr = np.array([1,3,5,7])
x = np.searchsorted(arr, [2,4,6])
print(x) # 반환값은 배열이다. [1,2,3] 순서를 유지하기 위해 원래 배열에 2,4,6이 삽입되는 인덱스가 포함

[1 2 3]
