## 2장 배열 인덱싱

In [ ]:
import numpy as np

In [4]:
# 배열의 요소를 가져오기
arr = np.array([1,2,3,4])
print('배열의 첫 번째 요소 확인:',arr[0])
print("배열의 두 번째 요소 확인:",arr[1])
print('배열의 세 번째 요소 확인:',arr[2])
print('배열의 네 번째 요소 확인:',arr[3])

배열의 첫 번째 요소 확인: 1
배열의 두 번째 요소 확인: 2
배열의 세 번째 요소 확인: 3
배열의 네 번째 요소 확인: 4


# 2차원 배열에 액세스

In [7]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print("첫번째 행의 두번째 열", arr[0,1])
print("두번째 행의 다섯번째 열", arr[1,4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
첫번째 행의 두번째 열 2
두번째 행의 다섯번째 열 10


# 3차원 배열에 액세스

In [10]:
arr = np.array([[[1,2,3,],[4,5,6]], [[7,8,9],[10,11,12]]])
print(arr)
print(arr[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


# 음수 인덱싱

In [12]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print('2차원에서의 마지막 원소:', arr[1, -1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2차원에서의 마지막 원소: 10
