## 1장 배열만들기

In [6]:
import numpy as np

In [7]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))   ##type() 함수를 이용해 전달된 객체의 유형을 알수있다.

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## 배열의 차원

In [11]:
## 0차원 배열
arr = np.array(42)
print(arr)
print(type(arr))

42
<class 'numpy.ndarray'>


In [12]:
# 값이 1,2,3,4,5를 포함하는 1차원 배열을 만든다
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [13]:
## 값이 1,2,3 및 4,5,6 인 두 개의 배열을 포함하는 2차원 배열을 만든다.
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [14]:
## 값이 1,2,3 및 4,5,6인 두 개의 배열을 포함하는 두 개의 2차원 배열을 사용하여 3차원 배열을 만든다.
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
print(type(arr))

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>


## 배열의 차원 수 확인

In [17]:
## NumPy array는 ndim 배열의 차원 수를 알려주는 정수를 반환하는 속성을 제
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print("차원 수 :", a.ndim)
print("차원 수 :", b.ndim)
print("차원 수 :", c.ndim)
print("차원 수 :", d.ndim)

차원 수 : 0
차원 수 : 1
차원 수 : 2
차원 수 : 3


## 고차원 배열

In [21]:
# 5차원 배열을 만들고 5차원인지 확인하
arr = np.array([1,2,3,4,5], ndmin=5)
print(arr)
print('차원 수 :', arr.ndim)

[[[[[1 2 3 4 5]]]]]
차원 수 : 5
