## 배열 분할

In [1]:
import numpy as np

In [4]:
# 3개 부분으로 분할
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)  #여기서 반환값은 3개의 배열을 포함하는 목록
print(arr)
print(arr.shape)
print("------------")
print(newarr)

[1 2 3 4 5 6]
(6,)
------------
[array([1, 2]), array([3, 4]), array([5, 6])]


In [5]:
# 4개 부분으로 분할
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,4)  #여기서 반환값은 4개의 배열을 포함하는 목록
print(arr)
print(arr.shape)
print("------------")
print(newarr)

[1 2 3 4 5 6]
(6,)
------------
[array([1, 2]), array([3, 4]), array([5]), array([6])]


## 분할된 배열 확인

In [9]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

newarr[0] = [7,8]   # 다른 요소로 변경가능
print(newarr[0])

[1 2]
[3 4]
[5 6]
[7, 8]


## 2차원 배열 분할하기

In [12]:
arr = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr = np.array_split(arr, 3)
print(arr)
print(arr.shape)
print("--------")
print(newarr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
(6, 2)
--------
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3)
print(arr)
print(arr.shape)
print("--------")
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
(6, 3)
--------
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [14]:
# 행 1로 지정
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis = 1)
print(arr)
print(arr.shape)
print("--------")
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
(6, 3)
--------
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
