# Array Join

In [ ]:
 import numpy as np

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1, arr2))
print(arr)
print(arr.shape)

[1 2 3 4 5 6]
(6,)


In [ ]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1, arr2), axis=1)  # 행 = 1
print(arr)
print(arr.shape)

[[1 2 5 6]
 [3 4 7 8]]
(2, 4)


## 스택함수

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)
print(arr.shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


## 행을 따라 쌓기

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.hstack((arr1, arr2))
print(arr)
print(arr.shape)

[1 2 3 4 5 6]
(6,)


## 열을 따라 쌓기

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.vstack((arr1,arr2))
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


## 높이를 따라 쌓기

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.dstack((arr1,arr2))
print(arr)
print(arr.shape)

[[[1 4]
  [2 5]
  [3 6]]]
(1, 3, 2)
