## 배열 반복

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [6]:
# 2차원 배열 반복
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [10]:
# 2차원 스칼라 요소 반복
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [11]:
# 3차원 배열 반복
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [12]:
# 3차원 스칼라 반복
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


## nditer()를 사용하여 배열 반복

`nditer()`매우 기본적인 반복부터 매우 고급 반복까지 사용할 수 있는 도움 기능이다. 반복에서 직면하는 몇 가지 기본적인 문제를 해결한다.

In [15]:
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


## ndenumerate()를 사용한 열거 반복

In [19]:
# 1차원
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [20]:
# 2차원
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [23]:
# 3차원
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8
(2, 2, 2)
