## 배열슬라이싱

In [2]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print(arr[1:5])  # 2번째 자리부터 4번째 자리까지 출력

[ 1  2  3  4  5  6  7  8  9 10]
[2 3 4 5]


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(arr[4:]) #4번째 자리부터 끝까지
print(arr[:4]) #처음부터 4번째 자리까지


[1 2 3 4 5 6 7]
[5 6 7]
[1 2 3 4]


# 음수 슬라이싱

In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(arr[-3:-1]) #뒤에서 3번째 자리 부터 뒤에서 1번 자리까지

[1 2 3 4 5 6 7]
[5 6]


# 단계 슬라이싱

In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(arr[1:5:2])  #[start : end : step] #[2번째자리 부터 : 5번째자리 전까지 : 2칸씩]
print(arr[::2])  # 전체 배열에서 짝수 빼고 출력

[1 2 3 4 5 6 7]
[2 4]
[1 3 5 7]


# 2차원 배열 분할하기

In [3]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[1, 1:4])  # 2번째 배열에서 2번째자리 부터 5번째자리 전까지
print(arr[0, 0:3]) # 1번째 배열에서 1번 자리부터 3번째자리 전까지
print(arr[0:2 , 2]) # 1번, 2번 배열에서 2번째 요소 모두 출력
print(arr[0:2, 1:4]) # 1번, 2번 배열에서 2번째 요소 부터 5번째자리전 요소까지 모두 출력

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]
[1 2 3]
[3 8]
[[2 3 4]
 [7 8 9]]
