## Array Shape

`shape` NumPy 배열에는 해당 요소의 수를 갖는 각 인덱스가 있는 튜플을 반환하는 속성

In [1]:
import numpy as np

In [7]:
arr = np.array([[1,2,3,4,],[5,6,7,8]])
print(arr)
print(arr.shape)
# (2, 4) 배열에 2차원이 있음을 의미한다. 첫번째 차원은 2개의 요소 두번째 차원은 4개의 요소

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [8]:
# ndim 활용
arr = np.array([1,2,3,4,], ndmin=5)
print(arr)
print("배열의 크기", arr.shape)

[[[[[1 2 3 4]]]]]
배열의 크기 (1, 1, 1, 1, 4)


## Array reshape

In [11]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])  # 1차원
print(arr)
print(arr.shape)
newarr = arr.reshape(4,3)  # 2차원으로 변경
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
# 1차원 -> 3차원 변경
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(arr)
print(arr.shape)
print(newarr)
print(newarr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


In [19]:
# 2차원 -> 3차원
arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
newarr = arr.reshape(2,3,2)
print(arr)
print(arr.shape)
print(newarr)
print(newarr.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


In [21]:
#3차원 -> 1차원
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # shape(2,2,3)
newarr = arr.reshape(-1)
print(arr)
print(arr.shape)
print(newarr)
print(newarr.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [22]:
#3차원 -> 2차원
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # shape(2,2,3)
newarr = arr.reshape(2,6)
print(arr)
print(arr.shape)
print(newarr)
print(newarr.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)
